Implement hooks in components of miniprogram
alipay/goldfish pull request #83
Opened 2021-04-20 08:34 UTC by yibuyisheng

* createComponent
* useState
* useEffect
* useReducer

2021-04-20 13:19 UTC, hi-yinyue requested changes

2021-04-20 13:19 UTC, hi-yinyue commented on packages/hooks/package.json
> +  "license": "ISC",
这个文件是 npm init 自动生成的吧，License 确定是这个么？

2021-04-20 13:19 UTC, hi-yinyue commented on packages/hooks/src/component/create.ts
> +export const isComponent2 = typeof my !== 'undefined' ? my.canIUse('component2') : false;
`!!window.my?.canIUse('component2')` 这样就可以了吧，不然只是判断非 undefined 也不严谨

2021-04-21 03:13 UTC, yibuyisheng commented on packages/hooks/src/component/create.ts
> +export const isComponent2 = typeof my !== 'undefined' ? my.canIUse('component2') : false;
> `!!window.my?.canIUse('component2')` 这样就可以了吧，不然只是判断非 undefined 也不严谨

小程序里面 window 是 `undefined`，所以可能要写成这样：
```ts
typeof my !== 'undefined' ? my?.canIUse('component2') : false;
```

2021-04-21 04:01 UTC, hi-yinyue commented on packages/hooks/src/component/create.ts
> +export const isComponent2 = typeof my !== 'undefined' ? my.canIUse('component2') : false;
my?.canIUse('component2') 可能返回 undefined，需要写成 `typeof my !== 'undefined' && !!my?.canIUse('component2')`

2021-04-21 06:25 UTC, yibuyisheng commented on packages/hooks/src/component/create.ts
> +export const isComponent2 = typeof my !== 'undefined' ? my.canIUse('component2') : false;
> my?.canIUse('component2') 可能返回 undefined，需要写成 `typeof my !== 'undefined' && !!my?.canIUse('component2')`

稳

2021-04-21 08:22 UTC, hi-yinyue approved these changes

2021-04-22 02:21 UTC, merged